import styles from '../../globals.module.css';
import {Membercard} from '@/app/components/member.js';
export default function Page() {
    return (
        <div className="container text-center mt-5">
            <h1 className={styles.title}>Meet Our Team</h1>
            <Membercard student={"Abhinav"} bio={"Bob."} studentID={2} department={"Website"}/>
            <Membercard student={"Vidit"} bio={"Vidit is a curious and creative learner who loves exploring new ideas. Whether he's building something with code, solving tricky puzzles, or diving into a new book, Vidit always brings enthusiasm and a positive attitude. He enjoys working with friends, asking great questions, and finding fun ways to learn and grow every day. "} studentID={3} department={"Website"}/>
            <Membercard student={"Ankur"} bio={"Ankur is a passionate and curious learner who loves to explore new ideas and concepts. He enjoys working on projects that challenge him to think critically and creatively. In his free time, Ankur likes to read, play video games, and spend time with friends."} studentID={4} department={"Website"}/>
            <Membercard student={"Anandita"} bio={"Anandita is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. She is passionate about technology and loves to work on projects that challenge her creativity and problem-solving skills. In her free time, Anandita enjoys reading, painting, and spending time with friends."} studentID={5} department={"Story"}/>
            <Membercard student={"Aurovik"} bio={"Aurovik is a curious and creative learner who loves to explore new ideas and concepts. He enjoys working on projects that challenge him to think critically and creatively. In his free time, Aurovik likes to read, play video games, and spend time with friends."} studentID={6} department={"Marcomm"}/>
            <Membercard student={"Brooklyn"} bio={"Brooklyn is a passionate and curious learner who loves to explore new ideas and concepts. She enjoys working on projects that challenge her to think critically and creatively. In her free time, Brooklyn likes to read, play video games, and spend time with friends."} studentID={7} department={"Story"}/>
            <Membercard student={"Khushi"} bio={"Khushi is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. She is passionate about technology and loves to work on projects that challenge her creativity and problem-solving skills. In her free time, Khushi enjoys reading, painting, and spending time with friends."} studentID={8} department={"Story"}/>
            <Membercard student={"Kristen"} bio={"Kristen is a passionate and curious learner who loves to explore new ideas and concepts. She enjoys working on projects that challenge her to think critically and creatively. In her free time, Kristen likes to read, play video games, and spend time with friends."} studentID={9} department={"Website"}/>
            <Membercard student={"Maryam"} bio={"Maryam is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. She is passionate about technology and loves to work on projects that challenge her creativity and problem-solving skills. In her free time, Maryam enjoys reading, painting, and spending time with friends."} studentID={10} department={"Story"}/>
            <Membercard student={"Mikaela"} bio={"Mikaela is a passionate and curious learner who loves to explore new ideas and concepts. She enjoys working on projects that challenge her to think critically and creatively. In her free time, Mikaela likes to read, play video games, and spend time with friends."} studentID={11} department={"Art & Design"}/>
            <Membercard student={"Nuha"} bio={"Nuha is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. She is passionate about technology and loves to work on projects that challenge her creativity and problem-solving skills. In her free time, Nuha enjoys reading, painting, and spending time with friends."} studentID={12} department={"Art & Design"}/>
            <Membercard student={"Philip"} bio={"Philip is a passionate and curious learner who loves to explore new ideas and concepts. He enjoys working on projects that challenge him to think critically and creatively. In his free time, Philip likes to read, play video games, and spend time with friends."} studentID={13} department={"Story"}/>
            <Membercard student={"Ruhi"} bio={"Ruhi is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. She is passionate about technology and loves to work on projects that challenge her creativity and problem-solving skills. In her free time, Ruhi enjoys reading, painting, and spending time with friends."} studentID={14} department={"Marcomm"}/>
            <Membercard student={"Samaira"} bio={"Samaira is a passionate and curious learner who loves to explore new ideas and concepts. She enjoys working on projects that challenge her to think critically and creatively. In her free time, Samaira likes to read, play video games, and spend time with friends."} studentID={15} department={"Marcomm"}/>
            <Membercard student={"Sameer"} bio={"Sameer is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. He is passionate about technology and loves to work on projects that challenge his creativity and problem-solving skills. In his free time, Sameer enjoys reading, painting, and spending time with friends."} studentID={16} department={"Website"}/>
            <Membercard student={"Seerat"} bio={"Seerat is a passionate and curious learner who loves to explore new ideas and concepts. She enjoys working on projects that challenge her to think critically and creatively. In her free time, Seerat likes to read, play video games, and spend time with friends."} studentID={17} department={"Art & Design"}/>
            <Membercard student={"Sidd"} bio={"Sidd is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. He is passionate about technology and loves to work on projects that challenge his creativity and problem-solving skills. In his free time, Sidd enjoys reading, painting, and spending time with friends."} studentID={18} department={"Marcomm"}/>
            <Membercard student={"Sparsha"} bio={"Sparsha is a passionate and curious learner who loves to explore new ideas and concepts. She enjoys working on projects that challenge her to think critically and creatively. In her free time, Sparsha likes to read, play video games, and spend time with friends."} studentID={19} department={"Art & Design"}/>
            <Membercard student={"Zoya"} bio={"Zoya is a dedicated and enthusiastic learner who enjoys exploring new ideas and concepts. She is passionate about technology and loves to work on projects that challenge her creativity and problem-solving skills. In her free time, Zoya enjoys reading, painting, and spending time with friends."} studentID={20} department={"Story"}/>
            
        </div>
    );
}